[package]
name = "te-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
cgmath = "0.18"
wgpu = "0.12"
winit = "0.26"
anyhow = "1.0"
bytemuck = { version = "1.4", features = [ "derive" ] }

[dependencies.gltf]
version = "1.0"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"